from pathlib import Path

import numpy as np


def load_flux_model(flux_file: Path) -> np.ndarray:
    """Loads the flux models generated by RvB's code."""
    return np.loadtxt(flux_file, comments="#", unpack=True)[:2]
